# __Slicing__

## __Agenda__

- NumPy Array Slicing
  * Slicing 1D NumPy Arrays
  * Slicing Using Step Value
  * Slicing: 2D Array
  * Slicing: 3D Array
  * Negative Slicing

## __1. NumPy Array Slicing__

- In Python, slicing refers to moving elements from one index to another.
- Instead of using an index, the slice is passed as **[start:end]**.
- Another way to pass the slice is to add a step as **[start:end:step]**.
- In slicing, if the starting is not passed, it is considered as 0. If the step is not passed as 1 and if the end is not passed, it is considered as the length of the array in that dimension.

### __1.1 Slicing 1D NumPy Arrays__

#### Example 1: Illustrate the use of slicing to retrieve employee ratings for a team of seven employees in the first quarter from an array

In [ ]:
import numpy as np
arr1d = np.array([1, 4, 3, 5, 6, 8, 9, 10, 12])

print(arr1d[1:7])

print(arr1d[::3])
print(arr1d[1])

[4 3 5 6 8 9]
[1 5 9]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

#### Example 2: Print the list of three subjects from the fourth index to the end

In [5]:
Books = np.array(['Physics','DataScience','Maths','Python','Hadoop', 'OPPs', 'Java', 'Cloud'])
print(Books[5:])
print(Books[5:6])
print(Books[5])

['OPPs' 'Java' 'Cloud']
['OPPs']
OPPs


### __1.2 Slicing Using Step Value__

In [3]:
X = np.array([8, 7, 6, 5, 4, 3, 2, 1])
print(X[1:6:3])
print(X[1::3])

[7 4]
[7 4 1]


### __1.3 Slicing: 2D Array__

In [8]:
Z = np.array([[11, 22, 33, 44, 55], [66, 77, 88, 99, 110]])
print(Z)
print(Z[0, 2:3])
print(Z[0, 2])

[[ 11  22  33  44  55]
 [ 66  77  88  99 110]]
[33]
33


### __1.4 Slicing: 3D Array__

In [26]:
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_3d)
slice_3d = array_3d[0,1:,1:]
print(slice_3d)
print(slice_3d.shape)
print(slice_3d.ndim)

slice_1d = slice_3d.reshape(1,2)
print(slice_1d)

slice_1d = slice_3d.reshape(-1)
print(slice_1d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[5 6]]
(1, 2)
2
[[5 6]]
[5 6]


### __1.5 Negative Slicing__
- Negative slicing is the same as negative indexing, which is interpreted as counting from the end of the array.

![image.png](attachment:c873726d-3a46-4967-9ae2-3bc9745078cf.png)

In [27]:
# Negative slicing for 1D array
Neg_slice = np.array([13, 34, 58, 69, 44, 56, 37,24])
print(Neg_slice[:-1])

[13 34 58 69 44 56 37]
